# Generated by Django 4.2.16 on 2024-11-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imageSec',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
    ]
